#!/usr/bin/env ruby
# Generated by the protocol buffer compiler. DO NOT EDIT!

require 'protocol_buffers'

module FYBER
  module UserConfiguration
    # forward declarations
    class Creative < ::ProtocolBuffers::Message; end
    class CreativeSeq < ::ProtocolBuffers::Message; end
    class Placement < ::ProtocolBuffers::Message; end
    class PlacementSeq < ::ProtocolBuffers::Message; end

    class Creative < ::ProtocolBuffers::Message
      set_fully_qualified_name "FYBER.userconfiguration.Creative"

      required :string, :id, 1
      required :float, :price, 2
    end

    class CreativeSeq < ::ProtocolBuffers::Message
      set_fully_qualified_name "FYBER.userconfiguration.CreativeSeq"

      repeated ::FYBER::UserConfiguration::Creative, :creative, 1
    end

    class Placement < ::ProtocolBuffers::Message
      set_fully_qualified_name "FYBER.userconfiguration.Placement"

      required :string, :id, 1
      repeated ::FYBER::UserConfiguration::Creative, :creative, 2
    end

    class PlacementSeq < ::ProtocolBuffers::Message
      set_fully_qualified_name "FYBER.userconfiguration.PlacementSeq"

      repeated ::FYBER::UserConfiguration::Placement, :placement, 1
    end

  end
end
